### ISSUE TITLE
Make non-static method instead of the static one

### ISSUE THREAD

**Issue by andtit2001** [VadimSam/dvpion-astroclub-prog#2]
This method is inconvenient to use:
https://github.com/VadimSam/dvpion-astroclub-prog/blob/c65950b80afea319e2383a2dc52e0cddde3ea999/Cpp/oop_001_hometask.cpp#L26

It should be used like that:
```cpp
// It would be great if prepending `const` qualifier to the next line did not break anything
/* const */ vector v;
std::cout << v.abs();
```

I highly recommend you rewrite the method.

**Comment by VadimSam** [comment]
``` c++
     double abs(double a, double b) {
        return sqrt(pow(a, 2) + pow(b, 2));
    }
```
```c++
    /* const */ vector vector;
```
```c++
vector.abs(system.planet1.v.x, system.planet1.v.y);
```
Something like that?

**Comment by andtit2001** [comment]
> Something like that?

No. It should be used like `system.planet1.v.abs()`

> And, do I calculate vector absolute value properly?

Well, you can use `hypot` function.

**Comment by VadimSam** [comment]
```c++
double abs() {
return hypot(x,y); //x and y was already defined before
}
```
```c++
system.planet1.r.abs(); //works fine
```

**Comment by andtit2001** [comment]
Nice!

Just remember...
> It would be great if prepending `const` qualifier to the next line did not break anything

But I do not insist on it. You can close the issue.
